language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install pijnu
  - python setup.py build_parsers
# command to run tests
script: nosetests tests
